// I need it in a separate file only to use
// using static TokenType.
public enum TokenType : ushort {
    Plus       = '+',
    Minus      = '-',
    Mul        = '*',
    Div        = '/',
    Equals     = '=',
    Exp        = '^',
    Mod        = '%',
    OParen     = '{',
    CParen     = '}',
    ORParen    = '(',
    CRParen    = ')',
    OSQParen   = '[',
    CSQParen   = ']',
    Colon      = ':',
    Semicolon  = ';',
    And        = '&',
    Or         = '|',
    Hash       = '#',
    At         = '@',
    SQuote     = '\'',
    DQuote     = '"',
    Dot        = '.',
    Comma      = ',',
    Ident      = 256,
    EndOfFile  = 257,
    Return     = 258,
    Literal    = 259,
}