// I need it in a separate file only to use
// using static TokenType.
public enum TokenType : ushort {
    Plus      = '+',
    Minus     = '-',
    Mul       = '*',
    Div       = '/',
    Equals    = '=',
    Exp       = '^',
    Mod       = '%',
    OParen    = '{',
    CParen    = '}',
    ORParen   = '(',
    CRParen   = ')',
    OSQParen  = '[',
    CSQParen  = ']',
    Colon     = ':',
    Semicolon = ';',
    And       = '&',
    Or        = '|',
    Hash      = '#',
    At        = '@',
    SQuote    = '\'',
    DQuote    = '"',
    Dot       = '.',
    Comma     = ',',
    Ident     = 256,
    String    = 257,
    Number    = 258,
    Char      = 259,
    Keyword   = 260,
}